import { Geist, Geist_Mono, Pattaya } from "next/font/google";
import "./globals.css";

// Load Google Fonts via next/font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pattaya = Pattaya({
  variable: "--font-pattaya",
  subsets: ["latin"],
  weight: "400",
});

// You can add the custom "Destine" font using the @font-face rule or import it directly from Google Fonts
const destine = {
  variable: "--font-destine",
  src: "url('https://fonts.gstatic.com/s/destine/v1/4JH7H2X7YF8Yk1kp49O5KIZsOoXqP5lMJXl-.woff2') format('woff2')",
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load Destine manually */}
        <link
          href="https://fonts.googleapis.com/css2?family=Destine&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pattaya.variable} ${destine.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
